USE [FIGO]
GO

/****** Object:  View [dbo].[V_VEHICLES]    Script Date: 25/05/2026 11:41:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO








ALTER VIEW [dbo].[V_VEHICLES]
AS

		SELECT 
		V.ID,
		V.VVIN,
		V.VENGINESERIAL,
		'' VBODYSERIAL,
		V.VPLATE,
		V.IDMODEL,
		V.IDCOLOR,
		M.IDBRAND,
		V.IYEAR,
		V.IDSUPPLIER,
		ISNULL(V.IDDEALER,0) AS IDDEALER ,
		ISNULL(V.IDCUSTOMER,0) AS IDCUSTOMER,
		V.BACTIVE,
		M.VDESCRIPTION AS VMODEL,
		B.VNAME AS VBRAND,
		C.VNAME AS VCOLOR,
		C2.VREFERENCE AS VSUPPLIER,
		ISNULL(C3.VFIRSTNAME,'') AS VDEALER,
		ISNULL(C4.VFIRSTNAME,'') AS VCUSTOMER,
		CASE WHEN V.IESTATUS=2 THEN 'TRANSITO' ELSE A.VDISPLAYESTATUS END AS VESTATUS,
		V.IESTATUS,
		V.DCREATED,
		V.ILASTKM
		FROM VEHICLE V WITH (NOLOCK)
		INNER JOIN MODEL M WITH (NOLOCK) ON M.ID=V.IDMODEL
		INNER JOIN BRAND B WITH (NOLOCK) ON B.ID=M.IDBRAND
		INNER JOIN COLOR C WITH (NOLOCK) ON C.ID=V.IDCOLOR
		INNER JOIN CONTACT C2 WITH (NOLOCK) ON C2.ID=V.IDSUPPLIER 
		INNER JOIN ACTION A WITH (NOLOCK) ON V.IESTATUS= A.ID
		LEFT JOIN CONTACT C3 WITH (NOLOCK) ON C3.ID=V.IDDEALER
		LEFT JOIN CONTACT C4 WITH (NOLOCK) ON C4.ID=V.IDCUSTOMER
GO


