
GO

/****** Object:  Table [dbo].[ADJUSTMENTDETAILS]    Script Date: 9/15/2025 11:34:40 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ADJUSTMENTDETAILS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDADJUSTMENT] [int] NOT NULL,
	[IDLOCATION] [int] NULL,
	[IDPART] [int] NOT NULL,
	[ISTOCK] [int] NOT NULL,
	[IDREASON] [int] NOT NULL,
	[CTYPE] [char](1) NOT NULL,
 CONSTRAINT [PK_ADJUSTMENTDETAILS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ADJUSTMENTDETAILS] ADD  CONSTRAINT [DF_ADJUSTMENTDETAILS_CTYPE]  DEFAULT ('E') FOR [CTYPE]
GO

ALTER TABLE [dbo].[ADJUSTMENTDETAILS]  WITH CHECK ADD  CONSTRAINT [FK_ADJUSTMENTDETAILS_ADJUSTMENT] FOREIGN KEY([IDADJUSTMENT])
REFERENCES [dbo].[ADJUSTMENT] ([ID])
GO

ALTER TABLE [dbo].[ADJUSTMENTDETAILS] CHECK CONSTRAINT [FK_ADJUSTMENTDETAILS_ADJUSTMENT]
GO

ALTER TABLE [dbo].[ADJUSTMENTDETAILS]  WITH CHECK ADD  CONSTRAINT [FK_ADJUSTMENTDETAILS_LOCATION] FOREIGN KEY([IDLOCATION])
REFERENCES [dbo].[LOCATION] ([ID])
GO

ALTER TABLE [dbo].[ADJUSTMENTDETAILS] CHECK CONSTRAINT [FK_ADJUSTMENTDETAILS_LOCATION]
GO

ALTER TABLE [dbo].[ADJUSTMENTDETAILS]  WITH CHECK ADD  CONSTRAINT [FK_ADJUSTMENTDETAILS_PART] FOREIGN KEY([IDPART])
REFERENCES [dbo].[PART] ([ID])
GO

ALTER TABLE [dbo].[ADJUSTMENTDETAILS] CHECK CONSTRAINT [FK_ADJUSTMENTDETAILS_PART]
GO

ALTER TABLE [dbo].[ADJUSTMENTDETAILS]  WITH CHECK ADD  CONSTRAINT [FK_ADJUSTMENTDETAILS_REASON] FOREIGN KEY([IDREASON])
REFERENCES [dbo].[REASON] ([ID])
GO

ALTER TABLE [dbo].[ADJUSTMENTDETAILS] CHECK CONSTRAINT [FK_ADJUSTMENTDETAILS_REASON]
GO

ALTER TABLE [dbo].[ADJUSTMENTDETAILS]  WITH CHECK ADD  CONSTRAINT [CK_ADJUSTMENTDETAILS_CTYPE] CHECK  (([CTYPE]='S' OR [CTYPE]='E'))
GO

ALTER TABLE [dbo].[ADJUSTMENTDETAILS] CHECK CONSTRAINT [CK_ADJUSTMENTDETAILS_CTYPE]
GO


