 
GO

/****** Object:  Table [dbo].[ADJUSTMENT]    Script Date: 9/15/2025 11:34:31 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ADJUSTMENT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDUSER] [int] NOT NULL,
	[IDSTATUS] [int] NULL,
	[IDSUPPLIER] [int] NOT NULL,
	[DCREATED] [datetime] NOT NULL,
	[VCOMMENT] [varchar](100) NULL,
	[DUPDATED] [datetime] NULL,
 CONSTRAINT [PK_ADJUSTMENT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ADJUSTMENT]  WITH CHECK ADD  CONSTRAINT [FK_ADJUSTMENT_STATUS] FOREIGN KEY([IDSTATUS])
REFERENCES [dbo].[ACTION] ([ID])
GO

ALTER TABLE [dbo].[ADJUSTMENT] CHECK CONSTRAINT [FK_ADJUSTMENT_STATUS]
GO

ALTER TABLE [dbo].[ADJUSTMENT]  WITH CHECK ADD  CONSTRAINT [FK_ADJUSTMENT_USER] FOREIGN KEY([IDUSER])
REFERENCES [dbo].[CONTACT] ([ID])
GO

ALTER TABLE [dbo].[ADJUSTMENT] CHECK CONSTRAINT [FK_ADJUSTMENT_USER]
GO


