USE [SODA]
GO

/****** Object:  View [dbo].[V_CONTACTS]    Script Date: 08/09/2025 10:06:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[V_CONTACTS]
AS


	SELECT 
		C.ID,
		C.VVAT,
		C.VFIRSTNAME,
		ISNULL(C.VLASTNAME,'') VLASTNAME,
		LTRIM(RTRIM(C.VFIRSTNAME+' '+ISNULL(C.VLASTNAME,''))) AS VFISCALNAME,
		C.IDCITY,
		CT.VNAME VCITY,
		CT.VSTATE,
		C.VADDRESS,
		C.VPHONE1,
		ISNULL(C.VPHONE2,'') VPHONE2,
		C.VEMAIL,
		ISNULL(C.IDBRAND,0) IDBRAND,
		ISNULL(B.VNAME,'') VBRAND,
		ISNULL(I.VLOGIN,'') VLOGIN,
		ISNULL(C.VREFERENCE,'N/A') VREFERENCE,
		ISNULL(C.DBIRTHDATE,'') DBIRTHDATE,
		ISNULL(C.BMALE,1) AS BMALE, 
		C.BCUSTOMER,
		C.BDEALER,
		C.BSUPPLIER,
		C.BUSER,
		C.BPROVIDER,
		C.BACTIVE,
		CASE WHEN C.BCUSTOMER =1 THEN 'CLIENTE'
			 WHEN C.BUSER =1 THEN 'USUARIO'
			 WHEN C.BDEALER = 1 THEN 'CONCESIONARIO'
			 WHEN C.BSUPPLIER = 1 THEN 'PLANTA'
			 ELSE 'PROVEEDOR' END AS VTYPE,
		ISNULL(C.IDPAYMETHOD,0) IDPAYMETHOD,
		ISNULL(C.IDGROUP,0) IDGROUP,
		ISNULL(C.IDAGENT,0) IDAGENT,
		ISNULL(X.VFIRSTNAME,'')+' '+ISNULL(X.VLASTNAME,'') AS VAGENT,
		C.BLOCKED
		FROM CONTACT C WITH (NOLOCK)
		INNER JOIN CITY CT WITH (NOLOCK) ON CT.ID=C.IDCITY
		LEFT JOIN BRAND B WITH (NOLOCK) ON B.ID=C.IDBRAND
		LEFT JOIN CONTACT X WITH (NOLOCK)  ON X.ID=C.IDAGENT
		LEFT JOIN INFOUSER I WITH (NOLOCK) ON I.IDUSER=C.ID
	
	
GO


