USE [SODA]
GO

/****** Object:  View [dbo].[V_DEALERS_USER]    Script Date: 09/09/2025 11:15:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



  
  
ALTER VIEW [dbo].[V_DEALERS_USER]  
AS  
  
SELECT U.ID AS IDUSER, U.VFIRSTNAME+ +U.VLASTNAME AS VUSER, D.ID AS IDDEALER, D.VFIRSTNAME AS DEALER  
FROM RELATED UC WITH (NOLOCK)  
INNER JOIN CONTACT U WITH (NOLOCK) ON U.ID=UC.IDUSER  
INNER JOIN CONTACT D WITH (NOLOCK) ON D.ID=UC.IDCONTACT  
WHERE   
U.BUSER =1 AND -- SEA UN USUARIO  
D.BDEALER=1 AND D.BUSER=0 -- RELACIONADO A UN CONCESIONARIO  
AND UC.IDUSER>1  
AND NOT EXISTS (SELECT * FROM [dbo].[V_SUPPLIERS_USER] SU WHERE SU.IDUSER=U.ID)  
UNION
SELECT DISTINCT S.IDUSER,S.VUSER,D.IDDEALER,D.DEALER 
FROM [dbo].[V_SUPPLIERS_USER] S
INNER JOIN V_DEALERS D ON D.IDSUPPLIER=S.IDSUPPLIER
GO


