USE [SODA]
GO

/****** Object:  View [dbo].[V_POLICYDETAILS]    Script Date: 04/09/2025 16:21:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






ALTER VIEW [dbo].[V_POLICYDETAILS]
AS
		SELECT 
			P.*,
			CASE 
				WHEN P.BVALID = 1 THEN 'VALIDO'
				WHEN P.BVALID = 0 AND EXISTS (
					SELECT 1 
					FROM POLICYDETAILS P2 WITH (NOLOCK)
					WHERE P2.ID = P.ID
					  AND P2.BVALID = 1
				) THEN 'NO REGISTRADO'
				WHEN P.BVALID = 0 THEN 'NO VALIDO'
				ELSE 'PENDIENTE'
			END AS VVALID
		FROM POLICYDETAILS P WITH (NOLOCK)
GO


