USE [SODA]
GO

/****** Object:  View [dbo].[V_SUPPLIERS_USER]    Script Date: 09/09/2025 11:13:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER VIEW [dbo].[V_SUPPLIERS_USER]
AS

SELECT U.ID AS IDUSER, U.VFIRSTNAME+ +U.VLASTNAME AS VUSER, S.ID AS IDSUPPLIER, S.VFIRSTNAME AS SUPPLIER
FROM RELATED UC WITH (NOLOCK)
INNER JOIN CONTACT U WITH (NOLOCK) ON U.ID=UC.IDUSER
INNER JOIN CONTACT S WITH (NOLOCK) ON S.ID=UC.IDCONTACT
WHERE 
U.BUSER =1 AND -- SEA UN USUARIO
S.BSUPPLIER=1 AND S.BUSER=0 -- RELACIONADO A UNA PLANTA
AND UC.IDUSER>1
UNION
SELECT U.ID AS IDUSER, 'ADMIN' AS VUSER,S.IDSUPPLIER, S.SUPPLIER
FROM CONTACT U WITH (NOLOCK) 
CROSS JOIN ( 
			 SELECT D.ID AS IDSUPPLIER, D.VFIRSTNAME AS SUPPLIER
			 FROM CONTACT D WITH (NOLOCK) 
			 WHERE D.BSUPPLIER=1 AND D.BUSER=0 -- RELACIONADO A UN CONCESIONARIO
			) S
WHERE U.ID=1 AND U.BUSER =1  -- SEA UN USUARIO


GO


