WITH TablaOrigen AS (
    SELECT
        TABLE_SCHEMA,
        TABLE_NAME,
        CAST(CHECKSUM_AGG(CHECKSUM(COLUMN_NAME, DATA_TYPE, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_PRECISION_RADIX)) AS VARCHAR(50)) AS TableChecksum
    FROM SODA.INFORMATION_SCHEMA.COLUMNS
    GROUP BY TABLE_SCHEMA, TABLE_NAME
),
TablaDestino AS (
    SELECT
        TABLE_SCHEMA,
        TABLE_NAME,
        CAST(CHECKSUM_AGG(CHECKSUM(COLUMN_NAME, DATA_TYPE, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_PRECISION_RADIX)) AS VARCHAR(50)) AS TableChecksum
    FROM OASIS.INFORMATION_SCHEMA.COLUMNS
    GROUP BY TABLE_SCHEMA, TABLE_NAME
)
SELECT
    ISNULL(S.TABLE_SCHEMA + '.' + S.TABLE_NAME, T.TABLE_SCHEMA + '.' + T.TABLE_NAME) AS TableName,
    CASE
        WHEN S.TABLE_NAME IS NULL THEN 'Solo en la base de datos de destino'
        WHEN T.TABLE_NAME IS NULL THEN 'Solo en la base de datos de origen'
        WHEN S.TableChecksum <> T.TableChecksum THEN 'Diferente'
        ELSE 'Igual'
    END AS Comparacion
FROM
    TablaOrigen AS S
FULL OUTER JOIN
    TablaDestino AS T ON S.TABLE_NAME = T.TABLE_NAME AND S.TABLE_SCHEMA = T.TABLE_SCHEMA
WHERE
    S.TABLE_NAME IS NULL OR T.TABLE_NAME IS NULL OR S.TableChecksum <> T.TableChecksum
ORDER BY
    ISNULL(S.TABLE_SCHEMA + '.' + S.TABLE_NAME, T.TABLE_SCHEMA + '.' + T.TABLE_NAME);