DELETE FROM [dbo].CONTACT 
WHERE ID NOT IN 
(
SELECT ID FROM CONTACT WITH (NOLOCK) WHERE ID=1
UNION
SELECT ID FROM CONTACT WITH (NOLOCK) WHERE BSUPPLIER=1
--UNION
--SELECT ID FROM CONTACT WITH (NOLOCK) WHERE BDEALER=1
UNION
SELECT ID FROM CONTACT WITH (NOLOCK) WHERE BUSER=1
)

UPDATE [ACCESSGROUPDETAIL] SET BASSIGN=1 WHERE IDACCESGROUP=1

DELETE FROM [dbo].[ADJUSTMENTDETAILS]
DELETE FROM [dbo].[ADJUSTMENT]
DELETE FROM [dbo].[ATTACHMENT] WHERE ID NOT IN (54,55,57,58)
DELETE FROM [dbo].[AUDIT]
DELETE FROM [dbo].[BACKORDER]
DELETE FROM [dbo].[COMMENT]
DELETE FROM [dbo].[DISPATCHEDCONTROL]
DELETE FROM [dbo].[GUIDEDETAILS]
DELETE FROM [dbo].[GUIDE]
DELETE FROM [dbo].[INVENTORY]
DELETE FROM [dbo].[INVOICECONTROL]
DELETE FROM [dbo].[LABORTIME]
DELETE FROM [dbo].[ITEM]
DELETE FROM [dbo].[LEVELUSER] WHERE IDUSER<>1
DELETE FROM [dbo].[LICENSE]
DELETE FROM [dbo].[LICENSEDETAILS]
DELETE FROM [dbo].[LOCATION]
DELETE FROM [dbo].[MAINTENANCEDETAILS]
DELETE FROM [dbo].[MAINTENANCE]
DELETE FROM [dbo].[MODEL]
DELETE FROM [dbo].[MOVEMENTDETAILS]
DELETE FROM [dbo].[MOVEMENT]
DELETE FROM [dbo].[MOVEMENTDETAILSPACKAGED]
DELETE FROM [dbo].[PACKAGE]
DELETE FROM [dbo].[PACKAGEDETAIL]
DELETE FROM [dbo].[PART]
DELETE FROM [dbo].[PARTMODEL]
DELETE FROM [dbo].[POLICYDETAILS]
DELETE FROM [dbo].[POLICY]
DELETE FROM [dbo].[POLICYTYPE]
DELETE FROM [dbo].[PRINTQUEUE]
DELETE FROM [dbo].[REMINDER]
DELETE FROM [dbo].[SALEORDERDETAIL]
DELETE FROM [dbo].[SALEORDER]
DELETE FROM [dbo].[VEHICLE]
DELETE FROM [dbo].[WAREHOUSE]
DELETE FROM [dbo].[ZONE]

